language: ruby
rvm:
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
services:
  - cassandra
before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
